server:
  port: 8887
  tomcat:
    uri-encoding: utf-8

github:
   client:
     id: e4933335661e02760104
     secret: 2d26643e10db23aa89bccec4990508219c23af9b
   redirect:
     url: http://127.0.0.1:8887/callback

spring:
  datasource:
    username: root
    password: lai159357
    url: jdbc:mysql://localhost:3306/xm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: lai159357
#    url: jdbc:h2:~/xm
#    driver-class-name: org.gjt.mm.mysql.Driver


